// GENERATED by scripts/build-arrival-edits.mjs — do not edit by hand.
//
// One 45-second edit per source recording in public/audio/arrival/. Re-run
// the script after adding a track to its LIBRARY table:
//
//   node scripts/build-arrival-edits.mjs
//
// Editing this file directly is pointless: the next run overwrites it.

import type { Track } from './site'

export const arrivalEdits: Track[] = [
  { title: "505", detail: "Arctic Monkeys", src: "/audio/arrival/505-arrival.m4a" },
  { title: "Apocalypse", detail: "Cigarettes After Sex", src: "/audio/arrival/apocalypse-arrival.m4a" },
  { title: "Sparks", detail: "Coldplay", src: "/audio/arrival/sparks-arrival.m4a" },
  { title: "Instant Crush", detail: "Daft Punk", src: "/audio/arrival/instant-crush-arrival.m4a" },
  { title: "Sextape", detail: "Deftones", src: "/audio/arrival/sextape-arrival.m4a" },
  { title: "Mockingbird", detail: "Eminem", src: "/audio/arrival/mockingbird-arrival.m4a" },
  { title: "Exit Music (For a Film)", detail: "Radiohead", src: "/audio/arrival/exit-music-arrival.m4a" },
  { title: "Pink + White", detail: "Frank Ocean", src: "/audio/arrival/pink-white-arrival.m4a" },
  { title: "Shinunoga E-Wa", detail: "Fujii Kaze", src: "/audio/arrival/shinunoga-e-wa-arrival.m4a" },
  { title: "On Melancholy Hill", detail: "Gorillaz", src: "/audio/arrival/melancholy-hill-arrival.m4a" },
  { title: "November Rain", detail: "Guns N' Roses", src: "/audio/arrival/november-rain-arrival.m4a" },
  { title: "Flashing Lights", detail: "Kanye West", src: "/audio/arrival/flashing-lights-arrival.m4a" },
  { title: "Midnight City", detail: "M83", src: "/audio/arrival/midnight-city-arrival.m4a" },
  { title: "Nothing Else Matters", detail: "Metallica", src: "/audio/arrival/nothing-else-matters-arrival.m4a" },
  { title: "Human Nature", detail: "Michael Jackson", src: "/audio/arrival/human-nature-arrival.m4a" },
  { title: "Nandemonaiya", detail: "RADWIMPS", src: "/audio/arrival/nandemonaiya-arrival.m4a" },
  { title: "Love of My Life", detail: "Queen", src: "/audio/arrival/love-of-my-life-arrival.m4a" },
  { title: "Suzume", detail: "RADWIMPS feat. Toaka", src: "/audio/arrival/suzume-arrival.m4a" },
  { title: "Shadow of the Day", detail: "Linkin Park", src: "/audio/arrival/shadow-of-the-day-arrival.m4a" },
  { title: "Space Song", detail: "Beach House", src: "/audio/arrival/space-song-arrival.m4a" },
  { title: "Borderline", detail: "Tame Impala", src: "/audio/arrival/borderline-arrival.m4a" },
  { title: "Something", detail: "The Beatles", src: "/audio/arrival/something-arrival.m4a" },
  { title: "Reflections", detail: "The Neighbourhood", src: "/audio/arrival/reflections-arrival.m4a" },
  { title: "After Hours", detail: "The Weeknd", src: "/audio/arrival/after-hours-arrival.m4a" },
  { title: "Call Out My Name", detail: "The Weeknd", src: "/audio/arrival/call-out-my-name-arrival.m4a" },
  { title: "Astrothunder", detail: "Travis Scott", src: "/audio/arrival/astrothunder-arrival.m4a" },
]
